## eric-enmsg-access-control image version

global:
  registry:
    url: armdocker.rnd.ericsson.se
    pullSecret:
  ingress:
    enmHost:
  timezone:
  enmProperties:
    COM_INF_LDAP_ADMIN_ACCESS:
    COM_INF_LDAP_PORT:
    COM_INF_LDAP_ROOT_SUFFIX:
    COM_INF_LDAP_ADMIN_CN:
    postgres_service:
    postgresql01_admin_password:
    default_security_admin_password:
    LDAP_ADMIN_CN:
    LDAP_ADMIN_PASSWORD:
productInfo:
  number: CXC 174 1909
  rstate: RSTATE
# Number of replicas(pods) to deploy
replicas-eric-enmsg-access-control: 1
images:
  eric-enmsg-access-control:
    name: eric-enmsg-access-control
    tag: VERSION
  waitInitContainer:
    enabled: true
    name: eric-enm-init-container
    tag: 1.7.0-1
    command: "[ '/bin/sh', '-c', 'bash /var/tmp/check_service.sh -s gossiprouter-cache,gossiprouter-remoting,jms01,postgres,sps,sso'
      ]"
  eric-enm-httpd:
    name: eric-enmsg-access-control-httpd
    tag: VERSION
  eric-enm-monitoring:
    enabled: true
    name: eric-enm-monitoring-eap6
    tag: 1.7.0-1
imageCredentials:
  repoPath: proj-enm
  pullPolicy: Always
  registry:
    url:
    pullSecret:
## Configure the service
## ref: http://kubernetes.io/docs/user-guide/services/
service:
  name: accesscontrol
  sgname: accesscontrol
  additionalServiceNames:
  - cacs-service
  annotations: {}
  labels: {}
ingress:
  enabled: true
ingress_jboss_web_context:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    enabled: true
    memory: 1536Mi
  limits:
    enabled: true
    memory: 4096Mi
  httpd:
    enabled: false
    requests:
      memory:
      cpu:
    limits:
      memory:
      cpu:
  monitoring:
    enabled: false
    requests:
      memory:
      cpu:
    limits:
      memory:
      cpu:
# LivenessProbe Health Check configuration.
livenessProbe:
  enabled: true
  command: /opt/ericsson/vmmonitord/bin/ocf_monitor.py
  arguments: --exec_agents
  initialDelaySeconds: 600
  timeoutSeconds: 15
  periodSeconds: 30
  failureThreshold: 1
readinessProbe:
  enabled: true
  command: /opt/ericsson/vmmonitord/bin/ocf_monitor.py
  arguments: --exec_agents
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 1
# Extra Annotations to be added to pod
podAnnotations: {}
## Tolerations for pod assignment
### ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []
## Affinity for pod assignment
### ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: requiredDuringSchedulingIgnoredDuringExecution
# Constrain which nodes your pod is eligible to be scheduled on
### ref:  https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature
nodeAffinity: {}
### ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/#pod-priority
priorityClassName: ""
## Node selector
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
nodeSelector: {}
#https://kubernetes.io/docs/reference/federation/extensions/v1beta1/definitions/#_v1beta1_deploymentstrategy
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
## Pod Disruption Budget is an indicator of the number of disruptions that can be tolerated at a given time.
podDisruptionBudget:
  maxUnavailable: 1
